package business

type RouterGroup struct {
	BusDictionaryRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	BusProviderRouter
	BusGoodsDictRouter
	BusGroupRouter
	BusOrderRouter
	BusFactoryRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
