package business

type RouterGroup struct {
	BusDictionaryRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	BusProviderRouter
	BusGoodsRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
